### ISSUE TITLE
Is there any way to run this with --allow-net? 

### ISSUE THREAD

**Issue by EduardsE** [muhibbudins/deno-watcher#1]
I'm trying to modify the bash script but it stops tracking file changes if I add the flag.

**Comment by amkayondo** [comment]
have you tried it out and what was the result

**Comment by hibuno** [comment]
Hi there,

Sorry in advance for the late response, this project will be archived. And I already create a new project with more flexibility to handle this operation here:

https://github.com/muhibbudins/denomon

Thank you
